package client.demo.model;

public class VisitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    private Long hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    private String visitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.status
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.host_id
     *
     * @return the value of t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public Long getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.host_id
     *
     * @param hostId the value for t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_url
     *
     * @return the value of t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public String getVisitUrl() {
        return visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_url
     *
     * @param visitUrl the value for t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setVisitUrl(String visitUrl) {
        this.visitUrl = visitUrl == null ? null : visitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.status
     *
     * @return the value of t_visit_log.status
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.status
     *
     * @param status the value for t_visit_log.status
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }
}