package client.demo.model;

import com.alibaba.fastjson.JSONObject;

public class VisitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    private Long hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    private String visitUrl;

    /**
     * 请求状态 Y正常 N错误 E内部错误 L请求拦截
     */
    private String status;
    /**
     * 额外信息记录
     */
    private JSONObject extend;

    /**
     * 记录是否有效，但凡成功 请求，则之前的失败都清空，失败请求次数置为0
     */
    private String valid;

    public String getValid() {
        return valid;
    }

    public void setValid(String valid) {
        this.valid = valid;
    }

    public JSONObject getExtend() {
        return extend;
    }

    public void setExtend(JSONObject extend) {
        this.extend = extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.host_id
     *
     * @return the value of t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public Long getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.host_id
     *
     * @param hostId the value for t_visit_log.host_id
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setHostId(Long hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.visit_url
     *
     * @return the value of t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public String getVisitUrl() {
        return visitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.visit_url
     *
     * @param visitUrl the value for t_visit_log.visit_url
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setVisitUrl(String visitUrl) {
        this.visitUrl = visitUrl == null ? null : visitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit_log.status
     *
     * @return the value of t_visit_log.status
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit_log.status
     *
     * @param status the value for t_visit_log.status
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    public void setStatus(String status) {
        this.status = status;
    }
}