package client.demo.dao;

import client.demo.model.VisitLog;
import client.demo.model.VisitLogExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface VisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int countByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int deleteByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int insert(VisitLog record);

    int insertExtend(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int insertSelective(VisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    List<VisitLog> selectByExample(VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") VisitLog record, @Param("example") VisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_log
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByExample(@Param("record") VisitLog record, @Param("example") VisitLogExample example);
}