package client.demo.dao;


import client.demo.model.VisitHost;
import client.demo.model.VisitHostExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface VisitHostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int countByExample(VisitHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int deleteByExample(VisitHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int insert(VisitHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int insertSelective(VisitHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    List<VisitHost> selectByExample(VisitHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    VisitHost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") VisitHost record, @Param("example") VisitHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByExample(@Param("record") VisitHost record, @Param("example") VisitHostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByPrimaryKeySelective(VisitHost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit_host
     *
     * @mbggenerated Thu Aug 26 11:15:21 CST 2021
     */
    int updateByPrimaryKey(VisitHost record);
}